### ISSUE TITLE
POST http://127.0.0.1:8000/conversation/send 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Skjsenses** [AfikDeri/Messenger-App-VueJS-and-Laravel#3]
![image](https://user-images.githubusercontent.com/43521715/54082209-e16b6c80-434c-11e9-895f-1041ea6c2cb5.png)

how can i fix?

**Comment by AfikDeri** [comment]
@Skjsenses Are you sure you have pusher installed through composer?

**Comment by ReardGjoni** [comment]
@Skjsenses have you found the solution?! I'm having the exact same problem

**Comment by AfikDeri** [comment]
@ReardGjoni Take a look at this comment, maybe it's a configuration issue
https://github.com/laravel/framework/issues/19059#issuecomment-299235989

**Comment by ReardGjoni** [comment]
@AfikDeri thanks for the reply, however I've already tried that(in this version the cluster is inside the .env variable but all the same), so it doesn't fix it.

**Comment by AfikDeri** [comment]
@ReardGjoni Interesting, maybe your .env vars are not read correctly.
Try running `php artisan config:cache` and see if it makes any difference.

**Comment by ReardGjoni** [comment]
I have tried most if not all of the solutions I have found online, including this one, please take a look at my repo if you would be so kind, I will add you as a contributor

**Comment by EduardAscanio** [comment]
In config\broadcasting.php
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
            ],

Change 'encypted' => true to false
